### ISSUE TITLE
Comentarios sobre Guia de objetos I

### ISSUE THREAD

**Issue by gorellano** [nictes1/LaboratorioIII#1]
Empleado.java

* Falta constructor con parametros
* En el metodo salarioAnual podes hacer return this.salario * 12;
* En el metodo aumento podes pasar que el parametro sea double y dentro: this.salario = this.salario + (this.salario * (porcentaje / 100)); Lo que muestra por consola lo meteria en el main y dentro del metodo
* El metodo getEmpleado haria un @Override al metodo toString ya que hereda todos los objetos de esta clase

Item.java

* Falta constructor con parametros
* En el caso del precioTotal podes poner en el constructor this.precioTotal = precioUnitario * cantidad;
* @Override
    public String toString() {
        return "ItemVenta{" +
                "id=" + id +
                ", descripcion='" + descripcion + '\'' +
                ", cantidad=" + cantidad +
                ", pUnitario=" + precioUnitario +
                ", pTotal=" + precioTotal +
                '}';
    }

Banco.java

* Los nombres de los metodos tienen que ir en mayusculas y si tiene mas de una palabras en camelCase
* Falta constructor con parametros
* Para credito y debito haria algo asi:

public double credito(double monto) {
        this.balance = this.balance + monto;
        return this.balance;
    }

public double debito(double monto) {
        if (this.balance < monto) {
            System.out.print("Monto insuficiente");
        } else {
            this.balance = this.balance - monto;
        }
        return this.balance;
    }

Hora.java

* Falta constructor con parametros
* Para aumentar y retroceder hora, min y segs haria algo asi:

public Hora(int hora, int minuto, int segundo) {
        this.hora = (hora >= 0 && hora < 24) ? hora : 0;
        this.minuto = (minuto >= 0 && minuto < 60) ? minuto : 0;
        this.segundo = (segundo >= 0 && segundo < 60) ? segundo : 0;
    }

    private void sumarHora() {
        if (this.hora == 23) {
            this.hora = 0;
        } else {
            this.hora++;
        }
    }

    private void sumarMinuto() {
        if (this.minuto == 59) {
            this.minuto = 0;
            sumarHora();
        } else {
            this.minuto++;
        }
    }

    public Hora sumarSeg() {
        if (this.segundo == 59) {
            this.segundo = 0;
            sumarMinuto();
        } else {
            this.segundo++;
        }
        return this;
    }

    private void retrocederHora() {
        if (this.hora == 0) {
            this.hora = 23;
        } else {
            this.hora--;
        }
    }

    private void retrocederMinuto() {
        if (this.minuto == 0) {
            this.minuto = 59;
            retrocederHora();
        } else {
            this.minuto--;
        }
    }

    public Hora retrocederSeg() {
        if (this.segundo == 0) {
            this.segundo = 59;
            retrocederMinuto();
        } else {
            this.segundo--;
        }
        return this;
    }

**Comment by nictes1** [comment]
Corregido.
